name: birchwoodstanhope.com
favicon: null
layout_spectrum: 0.5231160279363394
typography_spectrum: 0.766033377032727
title: 'Relocation, investment and lifestyle'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5156792823690921
  lightness: 0.7548488664906472
  saturation: 0.8536363213788718
  rhythmicContrast: 0.02019760780967772
purpose: []
